import json
import os

CONTRACTS = [
    ("Matchweek", "matchweekAbi", "matchweek"),
    ("PitchMkt", "pitchMktAbi", "pitch-mkt"),
    ("Treasury", "treasuryAbi", "treasury"),
    ("Disputes", "disputesAbi", "disputes"),
]

# faucet-stablecoin.ts is hand-maintained (not generated here, no Solidity counterpart)
# but still belongs in the barrel alongside the generated ABIs.
HAND_MAINTAINED_EXPORTS = ["faucet-stablecoin"]

OUTPUT_DIR = "/tmp/abis"


def main() -> None:
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    filenames = []
    for contract, export_name, filename in CONTRACTS:
        with open(f"out/{contract}.sol/{contract}.json") as f:
            abi = json.load(f)["abi"]
        content = (
            "// This file is auto-generated by pitchmkt/protocol. Do not edit manually.\n"
            f"export const {export_name} = {json.dumps(abi, indent=2)} as const;\n"
        )
        with open(f"{OUTPUT_DIR}/{filename}.ts", "w") as f:
            f.write(content)
        filenames.append(filename)

    index_lines = [f'export * from "./{name}";' for name in sorted(filenames + HAND_MAINTAINED_EXPORTS)]
    with open(f"{OUTPUT_DIR}/index.ts", "w") as f:
        f.write("\n".join(index_lines) + "\n")


if __name__ == "__main__":
    main()
