import json

CONTRACTS = [
    ("Matchweek", "matchweekAbi"),
    ("MatchweekFactory", "matchweekFactoryAbi"),
]

OUTPUT_PATH = "/tmp/abis.ts"


def main() -> None:
    lines = ["// This file is auto-generated by pitchmkt/protocol. Do not edit manually."]
    for contract, export_name in CONTRACTS:
        with open(f"out/{contract}.sol/{contract}.json") as f:
            abi = json.load(f)["abi"]
        lines.append(f"export const {export_name} = {json.dumps(abi, indent=2)} as const;")

    with open(OUTPUT_PATH, "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
